Gdcr2016
opitzconsulting/opitzconsulting.github.io pull request #28
Opened 2016-10-27 19:09 UTC by rattermeyer

Blog Posts zu den Coderetreats in Fulda / Essen

2016-10-28 22:24 UTC, codescape requested changes

2016-10-28 22:24 UTC, codescape commented on _posts/2016-10-26-gdcr2016.md
> +![Impressionen aus Fulda](/img/posts/2016-10-26/fulda1.jpg)
Mach doch hier noch einen Break davor und danach, damit das Bild nicht mitten im Text liegt.

2016-10-28 22:24 UTC, codescape commented on _posts/2016-10-26-gdcr2016.md
> +Am 22.10.2016 war wieder der Global Day of Codereteat.
Ein etwas längerer Aufmacher wäre super, da dieser ja auf der Übersichtsseite angezeigt wird. Vielleicht mit dem nächsten Satz zusammenziehen?

2016-10-28 22:24 UTC, codescape commented on _posts/2016-10-26-gdcr2016.md
> +Am Tag des Coderetreats das Problem "Game of Life" in mehreren Runden bearbeitet. Nach einem ersten Kennenlernen des Problems, steht dann die test-getriebene Entwicklung einer Lösung unter verschiede
Der "Rahmenbedingungen"-Satz ist ein wenig langatmig durch die verschachtelten Sätze.

2016-10-28 22:24 UTC, codescape commented on _posts/2016-10-26-gdcr2016.md
> +![Retrospektive](/img/posts/2016-10-26/DSC_1963_a.JPG)
Insgesamt gibt es drei Bilder aber nur zwei werden verwendet?

2016-10-29 16:47 UTC, rattermeyer commented on _posts/2016-10-26-gdcr2016.md
> +Am Tag des Coderetreats das Problem "Game of Life" in mehreren Runden bearbeitet. Nach einem ersten Kennenlernen des Problems, steht dann die test-getriebene Entwicklung einer Lösung unter verschiede
einizige Anmerkung mit der ich nicht übereinstimme...

2016-10-31 16:12 UTC, merged