Cattlecrew case management ui blog article
opitzconsulting/opitzconsulting.github.io pull request #34
Opened 2017-02-23 22:04 UTC by satspeedy

New blog article about published CattleCrew Case Management UI on GitHub

2017-02-24 07:30 UTC, rattermeyer requested changes
Super. Nur noch ein paar kleine Anmerkungen. Ein paar Dinge habe ich schon korrigiert.

2017-02-24 07:30 UTC, rattermeyer commented on _posts/2017-02-23-cattlecrew-case-management-ui-veroeffentlicht.md
> +Der vierte Tab-Reiter zeigt die ermittelten Daten an und speziell hilfreich für den Entwickler.
wahrscheinlich: und ist speziell

2017-02-24 07:30 UTC, rattermeyer commented on _posts/2017-02-23-cattlecrew-case-management-ui-veroeffentlicht.md
> +Es werden alle in der Engine existierenden Cases aufgelistet. Nach der Auswahl eines Cases können
Diese Aussage verstehe ich nicht: oben "New Case", aber es werden alle existierenden Cases aufgelistet und man wählt einen aus? Wahrscheinlich ist das eine Case Instanz?

2017-02-24 07:30 UTC, rattermeyer commented on _posts/2017-02-23-cattlecrew-case-management-ui-veroeffentlicht.md
> +## Used process engine
Benutzte Prozess Engine ?

2017-02-26 13:59 UTC, satspeedy commented on _posts/2017-02-23-cattlecrew-case-management-ui-veroeffentlicht.md
> +Der vierte Tab-Reiter zeigt die ermittelten Daten an und speziell hilfreich für den Entwickler.
jepp - pass ich an

2017-02-26 14:12 UTC, satspeedy commented on _posts/2017-02-23-cattlecrew-case-management-ui-veroeffentlicht.md
> +Es werden alle in der Engine existierenden Cases aufgelistet. Nach der Auswahl eines Cases können
Button "New Case" -> Starten einer neuen Case Instanz
Auflistung Links -> Auswahl einer Case Definitionen

Eine Case Definition muss aufgewählt werden, um von diesem eine neue Instanz zu starten.
Guter Punkt - ich versuche es deutlicher zu formulieren.

2017-02-26 14:13 UTC, satspeedy commented on _posts/2017-02-23-cattlecrew-case-management-ui-veroeffentlicht.md
> +## Used process engine
Ich nenne es "Eingesetzte Process Engine"

2017-02-26 14:58 UTC, satspeedy commented
Danke für das Feedback @rattermeyer. Ich habe es überarbeitet.

2017-02-26 18:38 UTC, merged